[package]
name = "tc"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
rust-i18n = "3.1.2"
sys-locale = "0.3.1"
tiktoken-rs = "0.5.9"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0.0"
tempfile = "3.12.0"