[package]
name = "tc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.40.0", features = ["fs", "io-util", "rt-multi-thread", "macros", "io-std"] }