[package]
name = "tc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tiktoken-rs = "0.5.9"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0.0"
tempfile = "3.12.0"